### ISSUE TITLE
Questions about the use of .h.in files

### ISSUE THREAD

**Issue by ScaledLizard** [libyal/libfmapi#4]
Hi and thanks for making libpff and all its submodules. 

I'm trying to compile a new version of libpff and I notice it has been split up into a lot of submodules. libfmapi is one of those submodules. It has various .h and .h.in files in the include subfolder. However, definitions.h.in and features.h.in can be copied to .h files that do not need editing. So I wonder: wouldn't it be better to have .h files directly instead of the .h.in files for these two files?

Additionally, there are types.h and types.h.in files. These files differ. Is it intentional then that types.h is checked in?

If there is truly a need to have several .h.in files, it would make life easier for me if there was a single config.h.in where all compiler settings are put in. This file should be used by the other .h files then.

Thanks for considering this
Björn

**Comment by joachimmetz** [comment]
> So I wonder: wouldn't it be better to have .h files directly instead of the .h.in files for these two files?

"Better" is subjective, the reason for having .h.in files is that part of the content is generated by autotools.

> Additionally, there are types.h and types.h.in files. These files differ. Is it intentional then that types.h is checked in?

There is no need that the .h file is checked in, this is likely a left over of earlier versions. 

> If there is truly a need to have several .h.in files, it would make life easier for me if there was a single config.h.in where all compiler settings are put in.

config.h.in can be found under common, it is generated by autotools

the role of config.h.in is different than the other .h.in files

**Comment by ScaledLizard** [comment]
Thanks for the information provided so far.

I'm trying to compile under Windows. I would prefer to use msvc, and cmake can generate Makefiles for msvc. However, libpff doesn't seem prepared for this way of building it. Even with msys2 I don't see how I can run the autotools. Do you have any solution for this, please? If I do succeed in building with cmake, would you accept a patch for the submodules? Likely, it would just add a CMakeLists.txt (I use .bat files to run cmake, but those are optional).

Since I likely won't be able to use the autotools, for me, fewer .h.in files would make things easier. Hence my original request.

The good thing about cmake is that it supports a wide range of compilers from a single project file.

**Comment by joachimmetz** [comment]
> Since I likely won't be able to use the autotools, for me, fewer .h.in files would make things easier. Hence my original request.

I understand, but IMHO git is a version control system not a source distribution platform.

> However, libpff doesn't seem prepared for this way of building it.  

The CI tests do this, I would recommend taking a look at these. However per https://github.com/libyal/libpff/wiki/Building the recommendation is to stick with the source distribution package of libpff

**Comment by ScaledLizard** [comment]
"IMHO git is a version control system not a source distribution platform"
I specifically checked out files from git so I can contribute via git. Is that not welcome here?

Are Windows executables available somewhere, please? That would save me a lot of work.

**Comment by joachimmetz** [comment]
> Are Windows executables available somewhere, please? That would save me a lot of work.

Nope, too time consuming, given that I have barely time for actual format analysis at this pont.

> I specifically checked out files from git so I can contribute via git. Is that not welcome here?

you can but, Cmake know that support is very low on the priority list and you would have to come up with solution that works for the whole of libyal and it is clear that it makes it easier, not that it just exchanges one problem for another. I'm not waiting to maintain yet another build system.

**Comment by ScaledLizard** [comment]
Thanks for your replies.

**Comment by ScaledLizard** [comment]
I created a cmake file for libbfio and I have sent a pull request. I hope you can accept the pull request, but please let me know if I did something wrong. I know a bit about git, but I'm still new to GitHub. Unfortunately, the cmake file does not process .h.in files. If you can accept the pull request, I can start creating cmake files for the other subprojects.

I was wondering if there is a repository of old versions available somewhere, before 2013? I am having trouble recovering emails, and I suppose that used to work in older versions. I would like to narrow down the version where that stopped working and ideally fix it. Unless you have information about it.

**Comment by joachimmetz** [comment]
> I created a cmake file for libbfio and I have sent a pull request. I hope you can accept the pull request, but please let me know if I did something wrong.

as I indicated before, I'd need a solution that works for the whole of libyal and that can reliably replace autotools. This should include:

* generating source from .l and .y files
* generating files from template files (.in)
* building binaries, including nearly static builds
* building Python bindings
* building OSSFuzz fuzz targets
* integration with gettext or other i18n/l10n support
* CI tests
* support for specific make targets like `make dist`, `make distclean`, `make sources`

> Unfortunately, the cmake file does not process .h.in files. 

What is the Cmake equivalent? the .in files help reduce a lot of unnecessary maintenance work

> I was wondering if there is a repository of old versions available somewhere, before 2013? 

There is https://github.com/libyal/legacy maybe that will provide you with the necessary relase.
