### ISSUE TITLE
Observed TEAMS related MAPI properties

### ISSUE THREAD

**Issue by gregfreemyer** [libyal/libfmapi#6]
I'm trying to work with a PST that has MAPI entries with message class (PidTagMessageClass ) values I haven't seen before:

- IPM.SkypeTeams.Message
- IPM.AppointmentSnapshot.SkypeTeams.Call
- IPM.AppointmentSnapshot.SkypeTeams.Meeting

Section 7.3 of "MAPI definitions.asciidoc" apparently needs entries for the above.

The PST with the MAPI entries with the above values originated as an Office365 exported PST with Teams data included.

Also, there are some additional properties unique to those message classes.

PR_TEAMS_REPLY_INFO is an example

I found PR_TEAMS_REPLY_INFO via an alternate tool.

I don't know what the full set of additional properties should be, nor how to find them.

**Comment by joachimmetz** [comment]
it is not an official document and best effort resource of observations. Feel free to send references, test data, a PR

**Comment by joachimmetz** [comment]
No response from reporter. Observation not reproducible without necessary data. Closing.
